### PR TITLE
Add vitepress documentation website

### LINKED ISSUE #38: Use Vitepress for documentation
Use vitepress for documentation instead of github wiki.

Would mean we would keep our documentation in the /docs directory in this repo as .md files.

Vitepress documentation: https://vitepress.dev/

We could probably use the following to automatically deploy to github pages, or write our own CI action to deploy elsewhere
https://github.com/marketplace/actions/vite-github-pages-deployer

### PR DESCRIPTION
**Pull request by scott97**
Closes #38 

This PR adds vitepress as a way to generate documentation from our /docs directory. 

#### Screenshots
image
image
image
image
image

### CODE REVIEW

**Review by trekhopton — CHANGES_REQUESTED** [review]
Unfortunately, changing the name of Capture-Sources.md has made the diff not work. Can you do file name changes in a separate PR please. Otherwise we can't tell what has changed.

**Comment by trekhopton** [comment]
Also, is project-overview.md a straight copy of the Readme?

**Comment by trekhopton** [comment]
It's good to have separate PRs for the configuration of a tool and then its use. A PR should make one clear change, simpler the better. This one is on the side of too many changes. Reviewer time is valuable so try and make PRs easy and clear to review.

**Comment by trekhopton** [comment]
Those screenshots look great! Very pretty documentation :)

**Comment by scott97** [comment]
> Unfortunately, changing the name of Capture-Sources.md has made the diff not work. Can you do file name changes in a separate PR please. Otherwise we can't tell what has changed.

Moved to separate PR

**Comment by scott97** [comment]
> Also, is project-overview.md a straight copy of the Readme?

Moved to separate PR

**Comment by scott97** [comment]
Did not mean to close this... Sorry

**Review by trekhopton — APPROVED** [review]

**Pull request merged**
