### PR TITLE
Update now creates non-extant entities

### PR DESCRIPTION
**Pull request by scruzin**
Also, add a helper function, `NewEntity`, to create a new entity.

### CODE REVIEW

**Review by trekhopton — APPROVED** [review]

**Comment by scruzin** [comment]
Can you take a look @scott97 at why this has broken some tests?

**Comment by scott97** [comment]
> Can you take a look @scott97 at why this has broken some tests?

```
=== RUN   TestUpdateUserForNonExistentEntity
    users_test.go:137: Did not receive expected error when updating non-existent user
```

I have a test for trying to update a non-existent entity which looks for an error that no longer occurs. In the openfish api clients can supply a partial object that only contains the parts of the entity to update. So if the entity does not exist, we can't create one since not all the information is guaranteed to be supplied by the client. I think it is easily fixable with no changes to the datastore package needed, I'll look into it.

**Comment by scott97** [comment]
Could we have our update function something like this? Takes an extra argument `upsert`  - update or insert in a single operation 

```go
func (s *CloudStore) Update(ctx context.Context, key *Key, fn func(Entity), dst Entity, upsert bool) error {
	_, err := s.client.RunInTransaction(ctx, func(tx *datastore.Transaction) error {
		err := tx.Get(key, dst)
		if err != nil && !(upsert && err == datastore.ErrNoSuchEntity) {
			return err
		}
		fn(dst)
		_, err = tx.Put(key, dst)
		return err
	})
	return err
}
```

**Comment by scruzin** [comment]
> > Can you take a look @scott97 at why this has broken some tests?
> 
> ```
> === RUN   TestUpdateUserForNonExistentEntity
>     users_test.go:137: Did not receive expected error when updating non-existent user
> ```
> 
> I have a test for trying to update a non-existent entity which looks for an error that no longer occurs. In the openfish api clients can supply a partial object that only contains the parts of the entity to update. So if the entity does not exist, we can't create one since not all the information is guaranteed to be supplied by the client. I think it is easily fixable with no changes to the datastore package needed, I'll look into it.

We've decided to revert to the original functionality.

**Pull request closed without merging**
